version: '3'
services:
  db:
    image:
      'mysql:5'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - license-network
  es01:
    image: elasticsearch:6.8.22
    container_name: es01
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks:
      - license-network
  kibana01:
    image: kibana:6.8.22
    container_name: kibana01
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 5601:5601
    networks:
      - license-network
  lvmeng:
    image: plosa/lvmeng:2.0
    container_name: lvmeng
    ports:
      - 8082:8080
    networks:
      - license-network
  compatiableTable:
    image: haohaoxuexi2/compatibility:v1
    container_name: compatibility
    ports:
      - 8083:5000
    networks:
      - license-network
networks:
  license-network:
    driver: bridge
