version: '3'
services:
  db:
    image:
      'mysql:5'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  kibana01:
    image: docker.elastic.co/kibana/kibana:7.13.0
    container_name: kibana01
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 5601:5601
