apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: compliance-openeuler-org-tls
spec:
  secretName: compliance-openeuler-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: compliance.openeuler.com
  dnsNames:
    - compliance.openeuler.org
