version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es01
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana01:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kibana01
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 5601:5601
    networks:
      - elastic
networks:
  elastic:
    driver: bridge